r"""
make_map.py — generate the structural half of the documentation.

    python make_map.py --entry app_v4.py --out MAP.md

ORIENTATION.md is written by hand: architecture, conventions, and the traps
that cost days. None of that can be derived from code.

THIS produces the part that can, and that goes stale the moment it is
written by hand — the stage order, the shape → target inventory, the
vocabulary size, the module graph, the entry points. Regenerate it whenever
the code changes and it cannot lie.

Read-only. AST and a pack import; nothing else runs.
"""
from __future__ import annotations

import argparse
import ast
import os
import sys

SKIP = {"__pycache__", ".git", ".venv", "venv", "_quarantine", "dvpath",
        "node_modules", "build", "dist"}


def _walk(root):
    for d, dirs, names in os.walk(root):
        dirs[:] = [x for x in dirs if x not in SKIP]
        for n in sorted(names):
            if n.endswith(".py"):
                yield os.path.join(d, n)


def _mod(p, root):
    m = os.path.relpath(p, root)[:-3].replace(os.sep, ".")
    return m[:-9] if m.endswith(".__init__") else m


def stage_order(root):
    """The stages run_pipeline calls, in source order — which IS the run
    order. Reading the call sites beats trusting a comment."""
    # FIND it rather than assume where it lives — a package can be
    # reorganised and this file should still report the truth.
    p = None
    for cand in _walk(root):
        if os.path.basename(cand) == "pipeline_run.py":
            p = cand
            break
    if not p:
        return []
    tree = ast.parse(open(p, encoding="utf-8", errors="ignore").read())
    fn = next((n for n in ast.walk(tree)
               if isinstance(n, ast.FunctionDef) and n.name == "run_pipeline"),
              None)
    if not fn:
        return []
    seen, out = set(), []
    for n in ast.walk(fn):
        if isinstance(n, ast.Call):
            name = getattr(n.func, "id", None) or getattr(n.func, "attr", None)
            if name and name.startswith("_stage_") and name not in seen:
                seen.add(name)
                out.append((name, n.lineno))
    return sorted(out, key=lambda r: r[1])


def pack_summary(pack_name="petroleum"):
    """Fields and shapes, from the pack itself."""
    try:
        from docshape.packs import load
        pk = load(pack_name)
    except Exception as e:
        return None, f"{type(e).__name__}: {e}"
    rows = []
    for name, sh in sorted(pk.shapes.items()):
        rows.append({
            "shape": name,
            "target": sh.get("target") or "—",
            "required": ", ".join(sh.get("required") or []),
            "optional": len(sh.get("optional") or []),
            "transforms": ", ".join(sh.get("transforms") or []) or "",
        })
    return {"fields": len(pk.fields), "shapes": rows,
            "noise": len(getattr(pk, "noise", ()) or ())}, None


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--entry", action="append", default=["app_v4.py"])
    ap.add_argument("--pack", default="petroleum")
    ap.add_argument("--out", default="MAP.md")
    a = ap.parse_args(argv)

    root = os.path.abspath(a.root)
    if root not in sys.path:
        sys.path.insert(0, root)

    L = []

    def out(s=""):
        L.append(s)

    out("# Data Wrangler — structural map")
    out()
    out("_Generated by `make_map.py` from the code. Do not edit — regenerate._")
    out()
    out("Companion to ORIENTATION.md, which carries the parts that cannot be")
    out("derived: why the system is shaped this way, and the traps.")
    out()

    # ── stages ───────────────────────────────────────────────────────────
    st = stage_order(root)
    out("## Pipeline stages, in run order")
    out()
    if st:
        out("Read from the call sites inside `run_pipeline()`, so this is the")
        out("real order rather than a remembered one.")
        out()
        for i, (name, ln) in enumerate(st, 1):
            out(f"{i}. `{name}`  — line {ln}")
    else:
        out("_could not read pipeline_run.py_")
    out()

    # ── vocabulary ───────────────────────────────────────────────────────
    pk, err = pack_summary(a.pack)
    out(f"## Vocabulary — pack `{a.pack}`")
    out()
    if err:
        out(f"_pack unavailable: {err}_")
    else:
        out(f"**{pk['fields']} fields · {len(pk['shapes'])} shapes · "
            f"{pk['noise']} noise tokens**")
        out()
        out("A shape with no target is recognised but has nowhere to land —")
        out("an open schema decision, not a bug.")
        out()
        out("| shape | target | required | optional | transforms |")
        out("|---|---|---|---:|---|")
        for r in pk["shapes"]:
            out(f"| `{r['shape']}` | `{r['target']}` | {r['required']} "
                f"| {r['optional']} | {r['transforms']} |")
    out()

    # ── module graph ─────────────────────────────────────────────────────
    files, mods, imports = {}, {}, {}
    for p in _walk(root):
        try:
            t = ast.parse(open(p, encoding="utf-8", errors="ignore").read())
        except SyntaxError:
            continue
        m = _mod(p, root)
        mods[m] = p
        files[p] = m
        got = set()
        for n in ast.walk(t):
            if isinstance(n, ast.Import):
                got |= {x.name for x in n.names}
            elif isinstance(n, ast.ImportFrom) and n.module:
                got.add(n.module)
                got |= {f"{n.module}.{x.name}" for x in n.names}
        imports[p] = got

    dependents = {p: set() for p in files}
    for p, got in imports.items():
        for imp in got:
            for cand in (imp, imp.rsplit(".", 1)[0] if "." in imp else None):
                if cand and cand in mods and mods[cand] != p:
                    dependents[mods[cand]].add(p)
                    break

    out("## Load-bearing modules")
    out()
    out("Imported by the most other modules. Read these before changing")
    out("anything they touch; a change here reaches a long way.")
    out()
    out("| module | imported by | KB |")
    out("|---|---:|---:|")
    ranked = sorted(dependents.items(), key=lambda kv: -len(kv[1]))[:20]
    for p, deps in ranked:
        if not deps:
            continue
        out(f"| `{files[p]}` | {len(deps)} | "
            f"{os.path.getsize(p) / 1024.0:.0f} |")
    out()

    # ── package sizes ────────────────────────────────────────────────────
    pkgs = {}
    for p, m in files.items():
        top = m.split(".")[0] if "." in m else "(root)"
        c, s = pkgs.get(top, (0, 0))
        pkgs[top] = (c + 1, s + os.path.getsize(p))
    out("## Packages")
    out()
    out("| package | modules | KB |")
    out("|---|---:|---:|")
    for top, (c, s) in sorted(pkgs.items(), key=lambda kv: -kv[1][1]):
        out(f"| `{top}` | {c} | {s / 1024.0:.0f} |")
    out()

    # ── entry points ─────────────────────────────────────────────────────
    out("## Entry points")
    out()
    for e in a.entry:
        out(f"- `{e}`")
    out("- `selftest.py` — the regression harness")
    out("- `codebase_census.py` — what is live, script, orphaned")
    out("- `dataview/import_data/pipeline_proc_runner.py` — the detached "
        "pipeline the UI spawns")
    out()

    text = "\n".join(L)
    with open(os.path.join(root, a.out), "w", encoding="utf-8") as f:
        f.write(text)
    print(text)
    print(f"\nwritten to {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
