@echo off
setlocal EnableExtensions
REM ===========================================================================
REM docs.bat - convert the component documents between Markdown and Word.
REM
REM   docs.bat towo rd            every .md in this folder -> .docx
REM   docs.bat tomd              every .docx in this folder -> .md
REM   docs.bat toword DataView_Database
REM   docs.bat tomd   DataView_Database
REM
REM WHY PANDOC BOTH WAYS
REM   The first version of these files was generated by a JavaScript library.
REM   They LOOKED slightly better and pandoc could not read them back —
REM   headings arrived as plain paragraphs and every `code span` lost its
REM   backticks, so a Word edit could not return to Markdown without hand
REM   repair. One tool in both directions round-trips: headings, tables,
REM   bullets, bold, italic and code all survive.
REM
REM   Verified on all five documents: 19/20/18/14/15 headings and 199/80/42/
REM   46/7 code spans recovered intact.
REM
REM WHICH COPY IS THE SOURCE
REM   Whichever you edited last. These convert in place, so pick one and
REM   convert the other FROM it - editing both and converting either way
REM   silently discards one set of changes. There is no merge here.
REM
REM REQUIRES pandoc:  winget install --id JohnMacFarlane.Pandoc
REM ===========================================================================

where pandoc >nul 2>&1
if errorlevel 1 (
    echo pandoc is not on PATH.
    echo   winget install --id JohnMacFarlane.Pandoc
    echo   then open a new shell so PATH is picked up.
    exit /b 2
)

set "ACTION=%~1"
set "ONE=%~2"
if "%ACTION%"=="" set "ACTION=toword"

REM The reference document carries the styling (fonts, heading colours, US
REM Letter, 0.75in margins). Without it pandoc uses its own defaults, which
REM are fine but will not match the rest of the set.
set "REF=%~dp0ref.docx"
set "REFARG="
if exist "%REF%" set "REFARG=--reference-doc=%REF%"
if not exist "%REF%" echo (no ref.docx beside this script - using pandoc's default styling)

if /i "%ACTION%"=="toword" goto :toword
if /i "%ACTION%"=="tomd"   goto :tomd
echo Unknown action "%ACTION%".  Use: toword ^| tomd
exit /b 2

REM ---------------------------------------------------------------------------
:toword
if not "%ONE%"=="" (
    call :one_word "%~dp0%ONE%.md"
    goto :eof
)
for %%F in ("%~dp0*.md") do call :one_word "%%~fF"
goto :eof

:one_word
if not exist "%~1" ( echo not found: %~1 & exit /b 1 )
echo %~nx1  ->  %~n1.docx
pandoc "%~1" %REFARG% -o "%~dp1%~n1.docx"
exit /b 0

REM ---------------------------------------------------------------------------
:tomd
if not "%ONE%"=="" (
    call :one_md "%~dp0%ONE%.docx"
    goto :eof
)
for %%F in ("%~dp0*.docx") do call :one_md "%%~fF"
goto :eof

:one_md
REM Never read the reference document back as content.
if /i "%~nx1"=="ref.docx" exit /b 0
if not exist "%~1" ( echo not found: %~1 & exit /b 1 )
echo %~nx1  ->  %~n1.md
REM --wrap=none keeps one paragraph on one line, so a later diff shows the
REM sentence that changed rather than every line after a re-wrap.
pandoc -f docx -t gfm --wrap=none "%~1" -o "%~dp1%~n1.md"
exit /b 0
